# Header
nav:
  # Posts: /archives
  # Categories: /category
  # Tags: /tag

# favicon
favicon: /favicon.png

# logo
logo: /images/logo.jpg

# links
links:
  #Github: https://github.com/rcy1314
  # ZhiHu:
  # Twitter: https://twitter.com/liangwenhao3
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: dark

# giscus
giscus:
  enable: 1
  repo: rcy1314/Idea
  repo_id: R_kgDOIhgfQA
  category: General
  category_id: DIC_kwDOIhgfQM4CS1EL
  mapping: pathname



