# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Idea
subtitle: "NOISE随记"
description: "念念不忘，必有回响"
keywords:
author: NOISE
language: cn
timezone: ""

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url:  https://rcy1314.github.io/Idea/       #替换为你自己的链接
root: /
permalink: posts/:abbrlink/    #这里就是永久链接的参数设置
permalink_defaults:

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex




# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: myscape

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: "git"
  repo: https://github.com/rcy1314/Idea
  branch: gh-pages



#RSS订阅
plugin:
  - hexo-generator-feed
#Feed Atom
feed:
  type: atom
  path: blread/atom.xml
  limit: 20

 # giscus
giscus:
  enable: 1
  repo: rcy1314/Idea
  repo_id: R_kgDOIhgfQA
  category: General
  category_id: DIC_kwDOIhgfQM4CS1EL
  mapping: pathname