menu: #TITLE: link
  About: about/
  Archives: archives/

profile_link: https://github.com/rcy1314/Idea-pen
avatar: https://cdn.staticaly.com/gh/rcy1314/tuchuang@main/NV/下载-(6).5room1dxwa80.jpg
favicon: https://cdn.staticaly.com/gh/rcy1314/tuchuang@main/NV/下载-(6).5room1dxwa80.jpg
gitment:
  username:
  repo:
  id:
  secret:

theme_color: 5badf0

disqus_shortname:

google_analytics: UA-XXXXXXXX-Y

twitter:

hitokoto: false #Output a Chinese sentence to description
instantclick: true #open INSTANTCLICK
service_worker: false #open SERVICE WORKER

js: #CDN
  instantclick: //cdnjs.loli.net/ajax/libs/instantclick/3.0.1/instantclick.min.js
  hitokoto: //v1.hitokoto.cn/?encode=js&select=%23hitokoto
  service_worker: /sw.js
  gitment: /js/gitment.browser.js

css: #CDN
  gitment:
