menu: #TITLE: link

  归档: archives/
  主页: https://noisework.cn

profile_link: https://github.com/rcy1314/Idea
avatar: https://cdn.staticaly.com/gh/rcy1314/tuchuang@main/NV/下载-(6).5room1dxwa80.jpg
favicon: https://cdn.staticaly.com/gh/rcy1314/tuchuang@main/NV/下载-(6).5room1dxwa80.jpg

# giscus
giscus:
  enable: 1
  repo: rcy1314/Idea
  repo_id: R_kgDOIhgfQA
  category: General
  category_id: DIC_kwDOIhgfQM4CS1EL
  mapping: pathname
theme_color: 5badf0

disqus_shortname:

google_analytics: 

twitter:

hitokoto: false #Output a Chinese sentence to description
instantclick: true #open INSTANTCLICK
service_worker: false #open SERVICE WORKER

js: #CDN
  instantclick: //cdnjs.loli.net/ajax/libs/instantclick/3.0.1/instantclick.min.js
  hitokoto: //v1.hitokoto.cn/?encode=js&select=%23hitokoto
  service_worker: /sw.js
  gitment: /js/gitment.browser.js

css: #CDN
  gitment:
