name: Hexo Auto Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 */2 * * * 
  workflow_dispatch:

# 这里放环境变量,需要替换成你自己的
env:
  # Hexo 编译后使用此 git 用户部署到 github 仓库
  GIT_USER: rcy1314
  # Hexo 编译后使用此 git 邮箱部署到 github 仓库
  GIT_EMAIL: 1129159201@qq.com
  # Hexo 编译后要部署的 github 仓库
  GIT_DEPLOY_REPO: rcy1314/Idea
  # Hexo 编译后要部署到的分支
  GIT_DEPLOY_BRANCH: gh_page
  # 注意替换为你的 GitHub 源仓库地址
  GIT_SOURCE_REPO: git@github.com:rcy1314/Idea.git
  # 哔哩哔哩专栏id
  BILIBILI_MID: 13950193
jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node_version: [16.15.0]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Bilibiliupdate
        run: |
          mkdir -p source/_posts
          python3 main.py '${{ env.BILIBILI_MID }}' '${{ env.GIT_DEPLOY_REPO }}' 
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          git add -A
          git commit -m 'Bilibili_update'
          git push origin main
          
      - name: Checkout deploy repo
        uses: actions/checkout@v3
        with:
        # 令 GitHub 在 git clone 和 git checkout 后「忘记」使用的 credentials。
        # 如果之后需要以另外的身份（如你的 GitHub Bot）执行 git push 操作时（如部署到 GitHub Pages），必须设置为 false。
        # persist-credentials: false
        # 拉取子模块(但是其HEAD是与repo里记录的一致,并非最新)
          submodules: true
          path: .deploy_git
          persist-credentials: false
            # 将子模块更新到最新
      - name: Update submodule
        run: git submodule update --remote    
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa e.coding.net >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa gitee.com >> ~/.ssh/known_hosts
          git config --global user.name 'rcy1314'
          git config --global user.email '1129159201@qq.com'
      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install
          npm uninstall hexo-generator-index --save
          npm install hexo-baidu-url-submit hexo-generator-index2 hexo-symbols-count-time hexo-blog-encrypt hexo-deployer-git --save
      - name: Deploy Hexo 
        run: |
        hexo clean
        hexo generate 
        hexo deploy
          
